version: "3.7"
services:
    db:
        container_name: post
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_DB: sbank
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            PGDATA: /var/lib/postgresql/data
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "8001:5432"
    pgadmin:
        container_name: post_admin
        image: dpage/pgadmin4:latest
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: yale918@gmail.com
            PGADMIN_DEFAULT_PASSWORD: 12345
            PGADMIN_LISTEN_PORT: 80
        ports:
            - "8002:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        links:
            - "db:pgsql-server"
volumes:
    db-data:
    pgadmin-data: